blog/urls.py
from . import views
from django.urls import include

from django.urls import path

app_name = 'blog'

urlpatterns = [
    path("", views.PostList.as_view(), name="home"),
    path("<slug:slug>/", views.PostDetail, name="post_detail"),
    path("category/<str:cats>/", views.CategoryList, name="category"),
]

wjb_personal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pages import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('resume/', views.resume_view, name='resume'),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

CATEGORIES = [
    ('MKT', 'Marketing'),
    ('P3D', '3D Printing'),
    ('FPV', 'FPV Drones'),
    ('WII', 'Portables'),
    ('WEB', 'Web Development'),
    ('COD', 'Other Coding'),
    ("OEE", 'Other Electronics'),
    ('SKI', 'Outdoors'),
    ('SPT', 'Sports'),
    ('KID', 'Kids'),
]


class Category(models.Model):

    name = models.CharField(choices=CATEGORIES, max_length=200, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home")


class Post(models.Model):

    STATUS = [('D', 'Draft'), ('P', 'Publish')]

    FEATURED = [('P', 'Primary'), ('S', 'Secondary')]

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    preview = models.CharField(max_length=255)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    content = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    featured = models.CharField(max_length=1, choices=FEATURED, blank=True)
    status = models.CharField(max_length=1, choices=STATUS, default='D')
    category = models.CharField(max_length=200, choices=CATEGORIES, default='WEB')
    image = models.ImageField(blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": str(self.slug)})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)

pages/models.py
from django.db import models

# Create your models here.

blog/forms.py
from .models import Comment, Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {'title', 'slug', 'preview', 'author', 'created_on', 'content', 'status', 'category', 'image'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.views import generic
from .models import Post, Category
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404


class PostList(generic.ListView):
    queryset = Post.objects.all()#.order_by("-created_on")
    extra_context = {'category_list': Category.objects.all()}
    template_name = "blog.html"
    paginate_by = 3


def CategoryList(request, cats):
    category_post = Post.objects.filter(category=cats)
    category_name = get_object_or_404(Category, name=cats)
    return render(request, 'blog_category.html', {'cats': category_name, 'category_posts': category_post, 'category_list': Category.objects.all()})


def PostDetail(request, slug):
    template_name = "blog_detail.html"
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True).order_by("-created_on")
    new_comment = None
    # Comment posted
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(
        request,
        template_name,
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        },
    )

pages/views.py
from django.shortcuts import render


# Create your views here.
def home_view(request, *args, **kwargs):  # *args, **kwargs
    return render(request, "home.html", {})


def resume_view(request, *args, **kwargs):
    return render(request, "resume.html", {})


def about_view(request, *args, **kwargs):
    my_context = {
        "title": "abc this is about us",
        "this_is_true": True,
        "my_number": 123,
        "my_list": [1313, 4231, 312, "Abc"],
        "my_html": "<h1>Hello World</h1>"

    }
    return render(request, "about.html", my_context)

templates/base.html
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>GrimlockFPV Website</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/MtMte-logo.ico' %}"/>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet"/>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet"/>

    {% block extra_head %}
    {% endblock extra_head %}

</head>

<body id="page-top">

{% include "navbar.html" %}

{% block content %}
{% endblock content %}


<!-- End your project here-->


{% include "footer.html" %}


{% include "script.html" %}

{% block extra_script %}
{% endblock extra_script %}

</body>

</html>

templates/base_blog.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GrimlockFPV Blog</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static './bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static './css/blog.css' %}" rel="stylesheet">
</head>
<body id="page-top">

{% include "navbar.html" %}

{% block content %}
{% endblock content %}

{% include "footer.html" %}

{% include "script.html" %}

{% block extra_script %}
{% endblock extra_script %}

</body>

</html>

templates/blog.html
{% extends 'base_blog.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="text-left">
                    <a class="blog-header-logo text-dark" href="#">Miscellaneous Musings</a>
                </div>
            </div>
        </header>
        {% include 'blog_nav.html' %}
    </div>


    <main class="container">
        {% for post in post_list %}
            {% if post.featured == 'P' %}
                <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                    <div class="col-md-6 px-0">
                        <h1 class="display-4 fst-italic">{{ post.title }}</h1>
                        <p class="lead my-3">{{ post.preview }}</p>
                        <p class="lead mb-0"><a href="{% url 'blog:post_detail' post.slug %}"
                                                class="text-white fw-bold">Continue
                            reading...</a></p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        {% for post in post_list %}
            {% if forloop.first %}
                <div class="row mb-2">
            {% endif %}
            {% if post.featured == 'S' %}
                <div class="col-md-6">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 justify-content-between align-items-center shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static center">
                            <a href="{% url 'blog:category' post.category %}">
                                <strong class="d-inline-block mb-2 text-primary">{{ post.get_category_display }}</strong>
                            </a>
                            <h3 class="mb-0">{{ post.title }}</h3>
                            <div class="mb-1 text-muted">{{ post.created_on }}</div>
                            <p class="card-text mb-auto">{{ post.preview }}</p>
                            <a href="{% url 'blog:post_detail' post.slug %}" class="stretched-link">Continue reading</a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <img src="{% static 'img/' %}{{ post.image }}" alt="..." class="img-thumbnail" width="200"
                                 height="250"
                                 preserveAspectRatio="xMidYMid slice" focusable="false">
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    From the Firehose
                </h3>
                {% for post in post_list %}
                    {% if post.featured != 'P' and post.featured != 'S' %}

                        <article class="blog-post">
                            <h2 class="blog-post-title">{{ post.title }}</h2>
                            <a href="{% url 'blog:category' post.category %}"><p
                                    class="blog-post-meta">{{ post.get_category_display }}</p></a>
                            <p>{{ post.content|safe }}</p>
                        </article>

                    {% endif %}
                {% endfor %}

                {% if is_paginated %}
                    <nav class="blog-pagination" aria-label="Pagination">
                        {% if page_obj.has_previous %}
                            <a class="btn btn-outline-primary"
                               href="?page={{ page_obj.previous_page_number }}">Older</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-outline-secondary disabled" href="?page={{ page_obj.next_page_number }}"
                               tabindex="-1"
                               aria-disabled="true">Newer</a>
                        {% endif %}
                    </nav>
                {% endif %}
            </div>
            {% include 'sidebar.html' %}
        </div>
    </main>
{% endblock content %}

templates/blog_category.html
{% extends 'base_blog.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="text-left">
                    <a class="blog-header-logo text-dark" href="#">GrimlockFPV on {{ cats.get_name_display }}</a>
                </div>
            </div>
        </header>
        {% include 'blog_nav.html' %}
    </div>
    <main class="container">
        {% for post in post_list %}
            {% if post.featured == 'P' %}
                <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
                    <div class="col-md-6 px-0">
                        <h1 class="display-4 fst-italic">{{ post.title }}</h1>
                        <p class="lead my-3">{{ post.preview }}</p>
                        <p class="lead mb-0"><a href="{% url 'blog:post_detail' post.slug %}"
                                                class="text-white fw-bold">Continue
                            reading...</a></p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        {% for post in category_posts %}
            {% if post.featured == 'S' %}
                {% if forloop.first %}
                    <div class="row mb-2">
                {% endif %}
                <div class="col-md-6">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 justify-content-between align-items-center shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static center">
                            <a href="{% url 'blog:category' post.category %}">
                                <strong class="d-inline-block mb-2 text-primary">{{ post.get_category_display }}</strong>
                            </a>
                            <h3 class="mb-0">{{ post.title }}</h3>
                            <div class="mb-1 text-muted">{{ post.created_on }}</div>
                            <p class="card-text mb-auto">{{ post.preview }}</p>
                            <a href="{% url 'blog:post_detail' post.slug %}" class="stretched-link">Continue reading</a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <img src="{% static 'img/' %}{{ post.image }}" alt="..." class="img-thumbnail" width="200"
                                 height="250"
                                 preserveAspectRatio="xMidYMid slice" focusable="false">
                        </div>
                    </div>
                </div>
            {% endif %}
        {% if forloop.counter|divisibleby:2 %}
            </div>
        {% endif %}
        {% endfor %}
        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    From the Firehose
                </h3>
                {% for post in category_posts %}
                    <article class="blog-post">
                        <h2 class="blog-post-title">{{ post.title }}</h2>
                        <p class="blog-post-meta">{{ post.created_on }}</p>
                        <p>{{ post.content|safe }}</p>
                    </article>
                {% endfor %}
                {% if is_paginated %}
                    <nav class="blog-pagination" aria-label="Pagination">
                        {% if page_obj.has_previous %}
                            <a class="btn btn-outline-primary"
                               href="?page={{ page_obj.previous_page_number }}">Older</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-outline-secondary disabled" href="?page={{ page_obj.next_page_number }}"
                               tabindex="-1"
                               aria-disabled="true">Newer</a>
                        {% endif %}
                    </nav>
                {% endif %}
            </div>
            {% include 'sidebar.html' %}
        </div>
    </main>

{% endblock content %}

templates/blog_detail.html
{% extends 'base_blog.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class="text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comments</h2>

        <p>
          {% endwith %} {% for comment in comments %}
        </p>

        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>

        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/blog_nav.html
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        {% for category in category_list %}
            <a class="p-2 link-secondary" href="{% url 'blog:category' category %}">{{ category.get_name_display }}</a>
        {% endfor %}
    </nav>
</div>

templates/footer.html
{% load static %}


<!-- Footer-->
<footer class="py-3 bg-dark">

    <!-- Social icons -->
    <div class="container">
        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
            <a href="https://www.facebook.com/mdbootstrap" target="_blank">
                <i class="fab fa-facebook-f mr-3"></i>
            </a>

            <a href="https://twitter.com/MDBootstrap" target="_blank">
                <i class="fab fa-twitter mr-3"></i>
            </a>

            <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
                <i class="fab fa-youtube mr-3"></i>
            </a>

            <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
                <i class="fab fa-google-plus-g mr-3"></i>
            </a>

            <a href="https://dribbble.com/mdbootstrap" target="_blank">
                <i class="fab fa-dribbble mr-3"></i>
            </a>

            <a href="https://pinterest.com/mdbootstrap" target="_blank">
                <i class="fab fa-pinterest mr-3"></i>
            </a>

            <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
                <i class="fab fa-github mr-3"></i>
            </a>

            <a href="http://codepen.io/mdbootstrap/" target="_blank">
                <i class="fab fa-codepen mr-3"></i>
            </a>
        </div>
    </div>
    <!-- Social icons -->
    <!--Copyright-->
    <div class="container px-5">
        <div class="p-4">
            <p class="m-2 text-center text-white">Copyright &copy;</p>
            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                <p class="m-0 text-center text-white">MtMte</p>
                <img src="{% static 'img/MtMte-logo.svg' %}" text-primary alt="MtMte Logo" width="32"
                     height="32">
                <p class="m-0 text-center text-white">Productions 2021</p>
            </div>
        </div>
    </div>
    <!--/.Copyright-->

</footer>

templates/navbar.html
<!-- Navigation-->

<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href=""></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                <li class="nav-item"><a class="nav-link" href="/resume/">Resume</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'blog:home' %}">Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class="text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comments</h2>

        <p>
          {% endwith %} {% for comment in comments %}
        </p>

        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>

        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/script.html
{% load static %}

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

templates/sidebar.html
<div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">
            <h4 class="fst-italic">About</h4>
            <p class="mb-0">Customize this section to tell your visitors a little bit about your
                publication,
                writers, content, or something else entirely. Totally up to you.</p>
        </div>

        <div class="p-4">
            <h4 class="fst-italic">Archives</h4>
            <ol class="list-unstyled mb-0">
                {% for category in category_list %}
                <li><a href="{% url 'blog:category' category %}">{{ category.get_name_display }}</a></li>
                {% endfor %}
            </ol>
        </div>

        <div class="p-4">
            <h4 class="fst-italic">Elsewhere</h4>
            <ol class="list-unstyled">
                <li><a href="#">GitHub</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
            </ol>
        </div>
    </div>
</div>
    